### ISSUE TITLE
trouble building

### ISSUE THREAD

**Issue by danomatika** [spacialdb/libpq.framework#2]
Howdy,

I had a little trouble building with the current version of Xcode but I managed to get it to work.
- build-libssl.sh failed (and I don't remember the reason now), so I updated it to the latest version
- The Prepare Framework shell script failed when trying to copy the headers.

I fixed it by changing:

```
cp -a "${BUILT_PRODUCTS_DIR}/${PUBLIC_HEADERS_FOLDER_PATH}/" "${BUILT_PRODUCTS_DIR}/libpq.framework/Versions/${FRAMEWORK_VERSION}/Headers"
```

to

```
cp -a "${TARGET_BUILD_DIR}/${PUBLIC_HEADERS_FOLDER_PATH}/" "${BUILT_PRODUCTS_DIR}/libpq.framework/Versions/${FRAMEWORK_VERSION}/Headers"
```

Note the change to **TARGET_BUILD_DIR**

**Comment by kashif** [comment]
@danomatika can you kindly have a play with it now? thanks!
