### ISSUE TITLE
Overly big pre-built framework

### ISSUE THREAD

**Issue by ioan-chera** [spacialdb/libpq.framework#3]
I've noticed that the pre-built framework is about 50MB uncompressed, 19MB compressed, and it's because the multiple versions within are actual copies, not symbolic links.

**Comment by kashif** [comment]
yes you are right! So sorry. Its because of not being symbolically linked... I've fixed that in the prebuild files now. Thanks for the issue! Can you kindly confirm all works?

**Comment by ioan-chera** [comment]
Yeah, it's correct now, thanks!

**Comment by kashif** [comment]
:+1:
