### ISSUE TITLE
Build for OS X?

### ISSUE THREAD

**Issue by iosdev-republicofapps** [spacialdb/libpq.framework#5]
Hi,

First, thanks so much for creating this project and for releasing it!  :-)

I'd like to use libpq.framework for a Mac OS X project.  Can you give me some hints as to what I need to change in libpq.framework to do that?  I'd be happy to make the changes on a branch of libpq.framework and submit a pull request to release it for OS X if you'd be interested in including a Mac version of the library.  I'm happy to do all of the work if you can give me some suggestions of what I might need to change.

Thanks!

**Comment by kashif** [comment]
hello! I will have a look and let you know the process... give me a few days

**Comment by iosdev-republicofapps** [comment]
Thanks!

**Comment by mmisesin** [comment]
For Mac OS X you don't need this framework
Just link with libpq framework, provided by system.
